spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangsheng512/config.git
          username: wangsheng512
          password: sheng930106
          basedir: H:/Companysourcecode/SpringCloud_Sell/config/basedir
  rabbitmq:
    host: 192.168.199.249
    username: guest
    password: guest
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh